#!/usr/bin/env bash
# This script is displays the content of the current directory in alist format where only the part of the name after the first dash is displayed
for i in *
do
    echo "$i" | cut -d'-' -f2
done
